services:
  mysql:
    image: mysql:8.0
    container_name: ${APP_NAME:-sns}_database
    restart: unless-stopped
    tty: true
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${DATABASE_PASSWORD:-docker}"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "${DATABASE_NAME:-sns_db}"
      MYSQL_USER: "${DATABASE_USERNAME:-docker}"
      MYSQL_PASSWORD: "${DATABASE_PASSWORD:-docker}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DATABASE_PASSWORD:-docker}"]
      retries: 3
      timeout: 5s
    networks:
      - sns-network

  nodejs:
    container_name: ${APP_NAME:-sns}_app
    build:
      context: .
      dockerfile: docker/node/Dockerfile
      args:
        - EXPOSE_PORT=${PORT:-3000}
    user: "1000:1000"
    ports:
      - '${PORT:-3000}:${PORT:-3000}'
    volumes:
      - .:/app
    depends_on:
      - mysql
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - sns-network

networks:
  sns-network:
    driver: bridge